controllers:
    resource: ../src/Controller/
    type: annotation

homepage:
    path: /homepage
    controller: App\Controller\HomepageController::home

create-album:
    path: /album/create
    controller: App\Controller\CreateAlbumController::createAlbum

add-review:
    path: /review/add
    controller: App\Controller\AddReviewController::addReview

view_reviews:
    path: /view/reviews
    controller: App\Controller\ViewReviewsController::viewReviews

profile:
    path: /profile
    controller: App\Controller\ProfileController::profile

edit-review:
    path: /review/edit/{id}
    controller: App\Controller\EditReviewController::editReview

kernel:
    resource: ../src/Kernel.php
    type: annotation
