controllers:
    resource: ../src/Controller/
    type: annotation

homepage:
    path: /homepage
    controller: App\Controller\HomepageController::home

create-album:
    path: /album/create
    controller: App\Controller\CreateAlbumController::createAlbum

edit-review:
    path: /review/edit
    controller: App\Controller\EditReviewController::editReview

view_reviews:
    path: /view/reviews
    controller: App\Controller\ViewReviewsController::viewReviews

profile:
    path: /profile
    controller: App\Controller\ProfileController::profile

kernel:
    resource: ../src/Kernel.php
    type: annotation
